# fly.toml app configuration file generated for ken-wheeler-aka on 2023-06-20T01:08:58+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ken-wheeler-aka"
primary_region = "arn"

[build]
  builder = "heroku/buildpacks:20"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

